sudo: required
services:
  - docker

before_install:
  - docker build -t philipobrien/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run philipobrien/react-test npm test -- --coverage

after_success:
  - docker build -t philipobrien/multi-client ./client
  - docker build -t philipobrien/multi-nginx ./nginx
  - docker build -t philipobrien/multi-server ./server
  - docker build -t philipobrien/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push those images to docker hub
  - docker push philipobrien/multi-client
  - docker push philipobrien/multi-nginx
  - docker push philipobrien/multi-server
  - docker push philipobrien/multi-worker